name: do-the-thing
on: [push]
jobs:
  test-awtfdb:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: sudo apt install -y libmagic1 libgraphicsmagick-q16-3 libgraphicsmagick1-dev
      - run: zig build test -freference-trace --verbose --verbose-link --verbose-cc
      # TODO crosscompile testing: https://github.com/lun-4/awtfdb/issues/1
      # TODO crosscompile testing: https://github.com/lun-4/awtfdb/issues/2
      - run: zig build
      - run: ci/smoketest.sh
  test-awtfdb-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: |
          brew update
          brew install gettext
      - run: zig build test -freference-trace --verbose --verbose-link --verbose-cc
      - run: zig build
      - run: ci/smoketest.sh
